### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by GermanKingYT** [Zaczero/Kumo#2]
First of all make sure that the nginx -s reload command is working properly

Edit the Nginx configuration nginx.conf file and add the following line include /etc/nginx/snippets/kumo.conf; (path must be the same as NginxBlockSnippetFile from Kumo config.json file)
/etc/nginx/snippets/kumo.conf here is a file but empty ? my config for kumo is in root  which path i need ?

Double-check that you have configured Nginx rate limiting properly and that you are getting user's real ip from the Cloudflare header (latest Cloudflare IP ranges)

Some examples ? dont know what i need to configure and what you need can you help me ?

**Comment by Zaczero** [comment]
`/etc/nginx/snippets/kumo.conf` is empty *by default*.
Once an IP gets blocked you should see it being populated ([related code](https://github.com/Zaczero/Kumo/blob/9edfd4cb57384996074d726fb8c7c2192b703b04/Kumo/Program.cs#L114)).
Just make sure Linux permissions allow Kumo process to write to that file.

For nginx rate limiting examples just search the web - it's open knowledge.
Example results:
1. https://www.nginx.com/blog/rate-limiting-nginx/
2. https://www.freecodecamp.org/news/nginx-rate-limiting-in-a-nutshell-128fe9e0126c/
3. https://dzone.com/articles/nginx-rate-limiting

It is a little hard at the beginning but once you get to know it, it will be super useful for you in the future if you decide to stick with nginx. Good luck ~!

**Comment by GermanKingYT** [comment]
Oct 09 16:46:46 testv555 nginx[22969]: nginx: [emerg] "deny" directive is not allowed here in /etc/nginx/snippets/kumo.conf:2
Oct 09 16:46:46 testv555 nginx[22969]: nginx: configuration file /etc/nginx/nginx.conf test failed
Oct 09 16:46:46 testv555 systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
 is that normal when i dos my server and i get blocked by kumo and want to restart nginx i get this error becouse nginx dont know this command or text 


# Created by Kumo
deny IP;

**Comment by GermanKingYT** [comment]
https://prnt.sc/uwaeq7

**Comment by Zaczero** [comment]
Looks like you have included kumo's ngnix snippet file in the wrong place.
Please do that inside of `http` section at `/etc/nginx/nginx.conf`.

**Comment by Zaczero** [comment]
@GermanKingYT Hey, do you still need help or can this issue be closed?
